apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: logging-group
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetNamespaces:
  - openshift-logging
