apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:  
  name: advanced-cluster-management
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: release-2.3
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: advanced-cluster-management.v2.0.3
