apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker
  namespace: amq-broker
  labels:
    operators.coreos.com/amq-broker.amq-broker: ''
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: 7.x
  installPlanApproval: Automatic
  name: amq-broker-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
