apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: camel-queue
  namespace: amq-broker
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acceptors:
    - expose: true
      name: openwire-acceptor
      port: 61616
      protocol: Core
    - expose: true
      name: amqp-acceptor
      port: 5672
      protocol: AMQP
  deploymentPlan:
    image: 'registry.redhat.io/amq7/amq-broker-rhel8:7.9-12'
    size: 1
    requireLogin: false
    persistenceEnabled: false
    journalType: nio
    messageMigration: false
    jolokiaAgentEnabled: false
    managementRBACEnabled: true
