apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: ex-aaoaddress
  namespace: amq-broker
spec:
  addressName: input-address
  queueName: input-queue
  routingType: anycast
