apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: jenkins-group
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  targetNamespaces:
  - jenkins
