apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jenkins-operator
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  channel: alpha
  installPlanApproval: Automatic
  name: jenkins-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: jenkins-operator.v0.4.1-rc3
