apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  master:
    containers:
      - image: 'quay.io/redhat-developer/origin-jenkins:4.7-stable'
        name: jenkins
  configurationAsCode:
    defaultConfig: true
    enableAutoReload: true
    enabled: true
