apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins
spec:
  master:
    containers:
      - image: 'quay.io/redhat-developer/origin-jenkins:4.7-stable'
        name: jenkins
  configurationAsCode:
    defaultConfig: true
    enableAutoReload: true
    enabled: true
