apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
  namespace: openshift-workspaces
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - oauthclients.finalizers.che.eclipse.org
spec:
  auth:
    #    identityProviderURL: ''
    #    identityProviderRealm: ''
    #    identityProviderImage: ''
    #    identityProviderClientId: ''
    #    externalIdentityProvider: false
    openShiftoAuth: true
  database:
    #    chePostgresUser: ''
    externalDb: false
      #    chePostgresHostName: ''
      #    chePostgresPassword: ''
      #    chePostgresDb: ''
      #    chePostgresPort: ''
  metrics:
    enable: true
  server:
    pluginRegistryImage: ''
    selfSignedCert: false
    devfileRegistryImage: ''
    tlsSupport: true
    cheFlavor: codeready
    cheImageTag: ''
    #    customCheProperties:
#      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "28800"
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 1Gi
    pvcStrategy: per-workspace
