apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-registry-operator
  namespace: amq-streams
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  channel: serviceregistry-1.1
  installPlanApproval: Automatic
  name: service-registry-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  #  startingCSV: service-registry-operator.v1.0.1
