apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  annotations:
    config.example.com/managed-by: gitops
    config.example.com/scm-url: git@github.com:redhat-cop/declarative-openshift.git
  labels:
    example: basic
    config.example.com/component: operators
    config.example.com/name: argocd-bootstrap
  name: argocd
  namespace: argocd
spec:
  #  version: v1.8.2
  dex:
    #    image: ghcr.io/dexidp/dex
    openShiftOAuth: true
      #    version: v2.27.0
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
      g, admins, role:admin
      g, developer, role:developer
      g, marketing, role:marketing
    scopes: '[groups]'
  server:
    route:
      enabled: true
