apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redhat-pull-secret
  namespace: quay
spec:
  encryptedData:
    .dockerconfigjson: AgAKxHASXGZweS15T133w9KS3Ac4iN/pdeRykT3xCXmBZ1BvlAWorG12uF/w+DDvqzeOUUiIrD+V3UUYh6NmY6NzzKdtnaVvAv9OHvnzBKds956XQClM1CSU7MBDCWtngobq2ihGGr1DBL6qugZQWqR5sNHmZmNRo53b5d4ftGWPmIjvQbY1/PdCFVNWjQX7dv1udy7M/fuRGV4Bu2uVV6fVFGVmUY7S8YSmZfKWjVodQVMwoabZUhP3ExVNPf4CPw2yB0Wwh9U3dAWA6bQIb/CNKM9ckAVD7NT+Dvz7pI6shnJrEhf3x1XymyGxlcbNa2eSERWAMTWeeieKav07S0NLY9Yet6fggDJu8N2bZ9QzIyID4UyueFBik7eh9Gpr0UJXDCTUqZ198eW4G+qyOzv/12OdbECcdh8rMA1Fh3EAng6Mis33nr2nhNuW2EHpT98ydQYDqcSswUTf6uGW74bWzQFQwssE8wjtodAwqPGb9I2W9Net6AUOV+AxwJqVdyUjdJjPa5V6OprWlgpeKcpo3YX5wFMJ6zVTa+8l9+IlPM4wqV1Tm12vr3uPOrOrAdH8msRzFBmzls4PLnAjlCCft7KbQbO2wGYTxbKFDk1MuYUOieSM8lz4fXt9odW1/9H6dOZRU9x01TJJa7IuqntxQwGgNWGmtpV6vWFaV0VFahsu71MW4m3JmCvKf1cXloyCK1kKavzPOsDNHhinQQAp2AOlXylJjpuPXjYFMJQziqzFp5c+8wNYO4mdpsvs3RSffPttfNvH9RV5xsy6EZzkQxpZbDSeHIxOdx2vQK/VsjJoGJC5rwjsRRdhntrNmIJa2w39BOAiPsS13CeEAIogtcggJQ8dc46X4qtJnsVmKhcdiG1kMxAyLYXaNyc0+SqE2FixI5XX9X7vl8IeZFGhHiGu1aPSMhoo4jdj6jBBBhaOqk/4NyPcPLVNsECzNopUVHyB7KdLrlO/5h0xjaSxCXRnNAD79MCZWKOXiq/6z2cNUHKHkay+N4UStX+xp4E0JOqHX4eEM/fjSkgGSlBp6TC4ODRLXmDk
  template:
    data: null
    metadata:
      name: redhat-pull-secret
      namespace: quay
    type: kubernetes.io/dockerconfigjson

