kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: knative-serving
  labels:
#    app.kubernetes.io/instance: serverless
    openshift.io/cluster-monitoring: 'true'
  annotations:
    openshift.io/display-name: 'Knative Serving'
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  finalizers:
    - kubernetes
