apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
  namespace: argocd
operation:
  initiatedBy:
    automated: true
spec:
  destination:
    namespace: sealed-secrets
    server: 'https://kubernetes.default.svc'
  project: cluster-setup
  source:
    path: sealed-secrets-operator/overlays/update-status
    repoURL: 'https://github.com/redhat-cop/gitops-catalog.git'
    targetRevision: HEAD
  syncPolicy:
    automated: 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true      
