apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    maintainer: 'Aly Ibrahim <aly@redhat.com>'
    repo-url: 'http://github.com/AlyIbrahim/openshift-add-ons.git'
  name: service-mesh
  namespace: argocd
spec:
  destination:
    namespace: service-mesh
    server: 'https://kubernetes.default.svc'
  project: cluster-setup
  source:
    path: service-mesh-operator
    repoURL: 'https://github.com/AlyIbrahim/openshift-add-ons.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
